{
  "comments": [
    {
      "key": {
        "uuid": "54d7b2cd_10d469c0",
        "filename": "client/run_isolated.py",
        "patchSetId": 5
      },
      "lineNbr": 486,
      "author": {
        "id": 1137164
      },
      "writtenOn": "2019-09-24T18:43:32Z",
      "side": 1,
      "message": "Why not surface the message from the OSError?",
      "revId": "00b9c939d211c01aa02f8c81337ca3692830cfe3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}