{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "d2935d47_ecd15a1a",
        "filename": "client/utils/file_path.py",
        "patchSetId": 1
      },
      "lineNbr": 96,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2021-03-01T07:45:20Z",
      "side": 1,
      "message": "Doesn\u0027t six.ensure_text work with encoding, errors arguments?\nhttps://six.readthedocs.io/#six.ensure_text",
      "range": {
        "startLine": 96,
        "startChar": 54,
        "endLine": 96,
        "endChar": 60
      },
      "revId": "b7db961030cf2dbb7c051816cc130f5c044d2dfc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}